### ISSUE TITLE
generated operation ids are very ugly

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#1003]
It is true that operation ids are not required, but what we are currently generating is quite ugly.  For example:

```yaml
paths:
  /test:
    get:
      # no operation id
      parameters: []
      responses:
        200:
          description: well done
```

Generates this for `operationId`:

```
get-/test
```

**Comment by buunguyen** [comment]
Please help clarify a bit. You say the generated IDs are ugly, but the example doesn't show any operation ID. So is the problem here is ID is ugly or it doesn't exist?

**Comment by webron** [comment]
@buunguyen the generated operationId is `get-/test` from what I can tell. It should be more like `getTest`.

**Comment by buunguyen** [comment]
Oh, I see. Thanks.

**Comment by webron** [comment]
Might be worth to try and find the relevant code in 2.x to see how it works. Should follow a similar flow. There are also edge cases - reserved words maybe, but also duplicate operationIds which must be avoided.

**Comment by buunguyen** [comment]
Ok. This is new to me. 

1. How can we check the operationID? Is it a field in the spec?
2. Can we have the rules documented here? Instead of me having to dig into 2.x codebase?

**Comment by webron** [comment]
My concern is that we've accumulated a lot of edge case handling over the years - that's why I suggested looking into the code base. However, I'll try to summarize things here.

The [`operationId`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationId) is an optional field in spec for each operation. It is used to uniquely identify an operation within a spec.

- It is *supposed* to be unique, but users can still make a mistake of giving the same id to two operations. The client should not break but make them unique still (by adding a sequential number after the opeartionId.
- The field does not have naming restrictions meaning it could contain spaces, slashes and other characters that are not development-language friendly. These need to be escaped/removed to be use. Again, remember the requirement for them to be unique.
- If the operationId exists with an empty value (either `""` or any whitespace), treat it as if there's no value.
- If an operationId does not exist, it's up to use to generate it. The value would be a combination of the HTTP verb for the operation + underscore (_) + the path where slashes are replaced by underscores and curly braces are removed.

For example, for `post /pet/{petId}/uploadImage`, the generated operationId would be `post_pet_petId_uploadImage`.

Again, there's a risk of conflict between generated operationIds and ones existing in the code, so those would be handled again by adding a numerical sequence at the end.

**Comment by buunguyen** [comment]
Thanks Ron. It's clear.

In the example by Tony, I suppose it should return `get_test`? Basically, without the slash?

**Comment by webron** [comment]
It should `get_test`, yes. It's not just without the slash, it's also an underscore instead of a hyphen.

**Comment by shockey** [comment]
### Plan

1. Modify existing tests to be aligned with specified functionality
2. Add tests for cases listed above that are currently uncovered by test suite
3. Make code changes to get passing tests
4. Confirm that the changes are encapsulated so that they minimally affect other parts of JS

**Comment by buunguyen** [comment]
Related issue https://github.com/swagger-api/swagger-js/issues/1013
