### ISSUE TITLE
calling an operation with a 4xx or 5xx response should throw an error

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#1005]
Currently we're not throwing an error if the server returns an error status.  This is different behavior from 2.x and should be changed such that status codes >= 400 throw an error

**Comment by buunguyen** [comment]
Fixed in https://github.com/swagger-api/swagger-js/pull/1015/files

**Comment by benirose** [comment]
Hey sorry to bump this old thread, but it looks like the code is throwing away the response body when throwing the error. This is incredibly bad for API design, because now APIs will have to return an untruthful status code in order to communicate details about the error back to the client. If I put in a PR to include the response body in the error thrown, will it be considered?

**Comment by benirose** [comment]
Sorry for the recent post, I should've looked at the latest version of the code.
