### ISSUE TITLE
Using SwaggerClient with resources with response code 302 

### ISSUE THREAD

**Issue by chamilaadhi** [swagger-api/swagger-js#1030]
Originally asked in https://github.com/swagger-api/swagger-ui/issues/2961
Hi ,
I'm using SwaggerClient (v 2.2.10). I'm calling a resource which returns HTTP status code 302 with a locaiton header. SwaggerClient does the redirection to the location header once it gets the response and my requirement is to only get the 302 response and not do the redirection request (I want to do the redirection from my code )

Is there any possibility to get the response (with 302 status code) and stop doing the redirection throught this client

Thanks

following is a sample code i use in my app to call the api

    var swaggerClient = new SwaggerClient({
         url: swaggerURL,
         success: function(swaggerData) {

             var application = {};

             swaggerClient["Application (individual)"].post_applications({
                     "body": application,
                     "Content-Type": "application/json"
                 },
                 function(data) {},
                 function(error) {}
             );
         }
     });

**Comment by fehguy** [comment]
Are you using this inside the browser or via node?  It's not possible, AFAIK, to _not_ follow the redirect in the browser.

**Comment by chamilaadhi** [comment]
I' using it inside the browser. Thanks for the reply btw

**Comment by shockey** [comment]
I'm going to close this due to inactivity, but wanted to add some thoughts.

@fehguy is correct, with swagger-client 2.x it's not possible to not follow the redirect, since the W3C spec for XMLHttpRequest specifies the following:

> If the origin of the URL conveyed by the Location header is same origin with the XMLHttpRequest origin and the redirect does not violate infinite loop precautions, transparently follow the redirect while observing the same-origin request event rules.

More here: https://stackoverflow.com/a/343359

With the latest version of swagger-client, it may be possible to use the `fetch` API's `redirect` option to throw an error or manually handle a redirect (see this though: https://stackoverflow.com/a/42717388), but we have never tested this functionality. It also definitely won't work in browsers that don't natively have fetch, because fetch polyfills are subject to the limitations of XMLHttpRequest.

Overall, I wouldn't recommend trying to implement this. If you have control over the API itself, you may consider providing a URL in the response instead of doing an HTTP redirect, which will allow you to make decisions on whether to follow the URL.
