### ISSUE TITLE
jsonpatch.apply is deprecated, please use `applyPatch` for applying patch sequences, or `applyOperation` to apply individual operations.

### ISSUE THREAD

**Issue by strongui** [swagger-api/swagger-js#1074]
I think the issue is caused by this package, that is used by swagger.js "fast-json-patch": "~1.1.8",

Upon Swagger init, the console spits this error out 30x. Screenshot attached.
![json-error](https://cloud.githubusercontent.com/assets/13644601/26784709/fba1b486-49cc-11e7-8961-1ad56e0cbfc3.jpg)

**Comment by shockey** [comment]
Thanks for the ticket!

You're correct - `fast-json-patch`'s 1.2 series deprecates the `apply` function that we use, which is not great.

There was a discussion in their repo about a bug that was causing our tests to fail with 1.2.0 of their package: https://github.com/Starcounter-Jack/JSON-Patch/issues/178

I tightened the `fast-json-patch` version for swagger-client in this PR last week:  https://github.com/swagger-api/swagger-js/pull/1071, so `swagger-client@3.0.13` (and swagger-ui as well) shouldn't have this problem going forward.

I'm closing because I think we've done all we can, since we can't keep previous versions of `swagger-client` from grabbing `fast-json-patch` 1.2.x. If you can suggest anything, please reply and I'll be happy to reopen.

Thanks again!
