### ISSUE TITLE
Overriding basePath

### ISSUE THREAD

**Issue by Cheprer** [swagger-api/swagger-js#1095]
Could add support for overriding of basePath in specification when loading from SwaggerUIBundle please?

This could fix the issue with multiple basePaths requested in here https://github.com/OAI/OpenAPI-Specification/issues/562 

At least for our case since we are using hapi views and then we can modify html context to render. So then you can use this context to modify basePath property when instantiating SwaggerUIBundle.

**Comment by Cheprer** [comment]
#1045

**Comment by char0n** [comment]
Hi Honza (@Cheprer) ;]

`swagger-js` (`swagger-client`) no longer needs to have mutators for `host`, `basePath` or `schemes` for OpenAPI 2.0.

Mutations can be achieved by current version 3.x in following way:

```js
(async () => {
  const { spec } = await new SwaggerClient({ url: 'https://petstore.swagger.io/v2/swagger.json' });
  spec.host = 'www.google.com';

  const swaggerClient = await new SwaggerClient({ spec });
  const response = await swaggerClient.apis.pet.findPetsByStatus({ status: 'available'}); // hits the www.google.com

  console.dir(response);
})();
```

Newer versions of `swagger-ui` use `swagger-js` 3.x in a new way (because in API changes of `swagger-js` 3.x). By implementing the explicit mutators on `swagger-js` (`setHost`, `setBasePath`, `setScheme`) directly wouldn't help solving the problem in `swagger-ui`. 

Addressing this issue should now be possible purely from `swagger-ui` by [UrlMutatorPlugin](https://github.com/swagger-api/swagger-ui/issues/5981).
