### ISSUE TITLE
2.2.21?

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#1112]
Looks like `@2.2.21` was accidentally published to npm. This means that `"^2.1.x"` will go to `@2.2.21` instead of `@2.1.32` (which was released later).

To work around this, since we are [not yet on 3.x](https://github.com/IBM-Bluemix/gp-js-client/issues/70) I am using `"2.1.x"` in my `package.json` which goes to `@2.1.32` properly.

Just noting this here.

**Comment by shockey** [comment]
Thanks for the note @srl295. 

Correct me if I'm wrong, but this seems like semver funkiness to me. I don't have a citation for this, but I'm fairly sure semver/npm makes version resolution decisions based on version numbers, not chronology.

`"^2.1.x"` is ambiguous, because the `^` allows both patch and minor version changes ([citation](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)), while a `2.1.x` mask only allows patch version changes (equivalent to a [tilde](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1)).

I can't find any docs that explain what should happen when a semver operator is paired with a masked comparator, but it would appear that the operator takes precedence, which allowed any minor versions in the `2` series, eventually resolving to `2.2.21`.

**Comment by srl295** [comment]
> but this seems like semver funkiness to me

to me also. 

I guess there is an [npm unpublish](https://docs.npmjs.com/cli/unpublish) which might really be the right thing™ here. I was misremembering that you can't unpublish a version, what you can't do is re-publish to the same number.

**Comment by srl295** [comment]
for me, i plan to fix this by moving to 3.x :)

**Comment by shockey** [comment]
Just picked this back up, and I see what you're saying now... there is no legitimate `2.2` series! My apologies, I wasn't involved in the `swagger-client@2` development, so I didn't know that off the top of my head.

Yeah, it seems like an unpublish of `swagger-client@2.2.21`is in order. @webron?

**Comment by shockey** [comment]
@webron bump

**Comment by char0n** [comment]
@srl295 thanks for reporting this. It's already been some time from the moment this issue has been reported and unpublishing it could cause problems to dependents already using this version. The affected version is marked as deprecated already and that should probably be enough.
