### ISSUE TITLE
prameters for parameter.in === 'body will always be overwritten with parameters[parameter.name]

### ISSUE THREAD

**Issue by nexinto-gmbh** [swagger-api/swagger-js#1132]
Hello,

I understand, that the execution of a requests needs an object of key:value pairs. This object will be split and applied to all neccessary parts of the request, based on in parameters of the spec.

`api.auth.login({ username: 'foo', password: 'bar' })`

I don't understand the following code from execution.js:

```
if(parameter.in === 'body' && parameter.schema && parameter.schema.properties) {
    value = parameters
}
value = parameter && parameter.name && parameters[parameter.name]
```

This code means, that if the paramter is a body in and some checks more, value will be parameters.
Ok, that is, what I expected.
But then `value` will be overwritten with `parameters[parameter.name]` if exists, otherwise with `undefined`.
So the `if(parameter.in === 'body' ...` block is useless.
Correct?

I know, that parameter.name for the body will be removed in OAI 3, but currently I must wrap my parameters with a body object.

`api.auth.login({body: { username: 'foo', password: 'bar' }})`

The (login) function call should be independend of the request structure, so it shouldn't be necessary to wrap the body parameter.

So this can be a fix:

```
if(parameter.in === 'body' && parameter.schema && parameter.schema.properties) {
    value = parameters
}
if(parameter && parameter.name && parameters[parameter.name]) {
    value = parameters[parameter.name]
}
```

Only use `parameters[parameter.name]` if it exists.

Thx

**Comment by shockey** [comment]
Hi @nexinto-gmbh!

I see what you mean, but we're not going to move away from wrapping Swagger 2 body parameters under the `body` name - it introduces a lot of ambiguity if you try to use freeform body parameters along with other parameters in the same operation.

As for OpenAPI 3.0, you provide your request body as `requestBody` instead of `body` :smile: 

I'm going to close this out, if you have any more thoughts feel free to reply!
