### ISSUE TITLE
Which parts of this library are not IE 10 compatible? [Question]

### ISSUE THREAD

**Issue by strongui** [swagger-api/swagger-js#1174]
What would it take to make it possible to use this with IE10? Does it simply require some polly-fills, or is swagger-js fundamentally incompatible with anything pre IE 11?

**Comment by shockey** [comment]
It's _probably_ just polyfills, since we transpile down to ES5, which IE10 supports.

There may be some oddities w/r/t the Fetch API, since it's not in IE at all - but the Fetch polyfill works well in IE11, at least.

It's mostly not supported because no one has ever made it a priority _to_ support it. We keep an eye on modern browser support (including IE11) with manual and automated testing, but we never look at IE10.

**Comment by strongui** [comment]
@shockey is there a way to find out what polyfills I'd need? Unfortunately I still have to support IE 10 :(

**Comment by shockey** [comment]
@strongui Try to run things :smile: off the top of my head, You'll certainly need the Fetch API polyfill. Promises should be covered by `babel-runtime` in our build process, so you shouldn't need a Promise polyfill.

Beyond that, I'm not very familiar with the ins and outs of IE11's JS support, but feel free to ping me here if you encounter any cryptic errors.

**Comment by strongui** [comment]
@shockey haha alright cool :) thanks for the help I'll give it a go!
