### ISSUE TITLE
operationId converted to underscore 

### ISSUE THREAD

**Issue by palanik** [swagger-api/swagger-js#1251]
As per Open API specifications, [operationId](https://swagger.io/specification/#operationId) is only  RECOMMENDED to follow common programming naming conventions.

We define operationId in our endpoints with with the following convention.
`resource.operation`
e.g.: `user.list`, `user.update`, `user.create` etc.
This matches with our client sdk function names - `user.list()`.

This doesn't actually violate the spec. But, the UI converts the `.` to `_`.

I traced this change back to this [commit](https://github.com/swagger-api/swagger-js/commit/361a51db51e0d7c24ce2bdc45679ce096dae0c94#diff-b38f7254be1a9f817fd2e33c294481a1R4). 

Would like to know the reason for this change. 
(I couldn't find an issue associated with the commit)

Also, is it possible to revert the change or additional change to display the operationId as defined, while use the converted value in other places?

**Comment by webron** [comment]
I believe the `operationId` changes are due to language naming constraints, though @shockey can comment more on that. We _should_ be able to provide the original `operationId` as provided though, for documentation purposes.

**Comment by shockey** [comment]
Hi @palanik!

Yep, as @webron noted, the conversion and escaping step was added to (a) ensure operationId uniqueness and (b) make Swagger-Client's tags interface more user-friendly: `client.apis.user_list()` is nicer than `client.apis.['user.list']()`, since you can't use dot-notation to access member keys with dots in their name.

It sounds like you're seeing these escaped operationIds in the UI when `displayOerationId` is enabled, am I correct?

If so, that's a bug, probably introduced by one of the recent PRs that touched the OperationContainer. The UI is meant to display operation IDs as they are written in the definition.

An API definition that demonstrates this problem would go a long way towards helping us get this fixed :smile:

**Comment by palanik** [comment]
Hi @webron, @shockey,

Thanks for the quick response.

Your assumption is correct. I am seeing the escaped (with underscore) operationId in the UI when `displayOperationId` is enabled.

With the operationId set as `operationId: "app.info"`, this is what is displayed on the UI.
![image](https://user-images.githubusercontent.com/1656913/36703358-4ff64c30-1b29-11e8-94e5-1db736d0ab38.png)

I have a different opinion on using dot-notation for function names.  😄
I prefer dot-notation because if feels natural and some client sdk's use that. Most popular one being [Slack Web API](https://api.slack.com/web)
It groups the methods nicely under a resource.

Taking your example, it is absolutely possible to build an interface like `client.apis.user.list()`, `client.apis.user.update()` etc. in JavaScript. 

Thanks again for looking into this.

**Comment by palanik** [comment]
Followup, I was using `swagger-ui-dist` version `3.9.2`, where I experienced this issue.

Looks like it is fixed with the most recent version - `3.11.0`.

I should have checked. Sorry for the trouble. 

You can close this issue.

**Comment by webron** [comment]
Thanks @palanik.
