### ISSUE TITLE
Execute is not throwing error when the parameter expected is not provided

### ISSUE THREAD

**Issue by kavisuresh** [swagger-api/swagger-js#1271]
Execute is currently not throwing any error  when the parameter expected is not provided, which causes the code to hang and time out and we get "UnhandledPromiseRejectionWarning: Unhandled promise rejection "

**Comment by shockey** [comment]
Hi @kavisuresh!

This is by design. Since you're getting `UnhandledPromiseRejectionWarning`, I assume you're in Node.js 7 or earlier - in newer versions of Node, your process would exit with code 1.

You can capture any error that execute gives you by adding a catch handler to the Promise that execute returns. If you want to just throw, here's how you'd do that:

```js
Swagger.execute({...})
  .then(res => console.log(res))
  .error(err => throw new Error(err))
```

It's just a callback function, so you could do anything else with that error you wanted to, like consume it in your application, display it to the user, etc.

Hope this helps!

**Comment by kavisuresh** [comment]
Hi @shockey 

 I have a catch block to handle the error, but what I observed is , I get the below message 
(node:2593) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Required parameter ab_test_id is not provided

but the control doesn't go to then or catch block - it just gets timed out

**Comment by shockey** [comment]
@kavisuresh, are you using the static `execute` method like I illustrated above, or the instance method, more like this:

```js
    Swagger('http://localhost:8000/petstore.yaml')
      .then(client => {
        client.execute({
          operationId: "findPetsByStatus"
        })
      })
```

**Comment by kavisuresh** [comment]
Hi @shockey,  I am using the instance method

**Comment by shockey** [comment]
I've opened #1281 to fix this, but it introduces some interface changes that I'd like to sit with for a bit before moving forward 😄

**Comment by shockey** [comment]
@kavisuresh, in the meantime, catching at the top level of Swagger-Client will work:

```js
    Swagger('http://localhost:8000/petstore.yaml')
      .then(client => {
        client.execute({
          operationId: "findPetsByStatus"
        })
      })
      .catch(e => console.error(e))
```

**Comment by char0n** [comment]
@kavisuresh the `execute` method can produce two types of errors.

**Programmer Error**

Is [thrown](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) synchronously as classical Error. Happens when you did not provided an expected argument.

**Operation Error**

When unexpected things happen e.g. during making actual HTTP request (network errors etc). These errors are delivered asynchronously via promise chains.


_Explanation on code examples:_
```js
new SwaggerClient({ url: 'https://petstore.swagger.io/v2/swagger.json' })
  .then(client => {
    try {
      return client.execute({
        operationId: "findPetsByStatus"
      });
    } catch(e) {
       // do something here about the error
    }
  })
```

_Catch in top level promise handler:_

```js
new SwaggerClient({ url: 'https://petstore.swagger.io/v2/swagger.json' })
  .then(client => client.execute({
    operationId: "findPetsByStatus"
  })
  .catch(error => {
    // error here can either be programmer or operation error
    // do something here about the errors
  });
```

The original error of `UnhandledPromiseRejectionWarning: Unhandled promise rejection` that you've been getting was probably caused by the fact that you did not return the result of the `execute` instance method back to the promise chain.

**Wrong usage:**
```js
    SwaggerClient('https://petstore.swagger.io/v2/swagger.json')
      .then(client => {
        client.execute({  // this promise will get lost in limbo and is not sychronized
          operationId: "findPetsByStatus",
          status: 'available',
        })
      })
     .catch(error => console.error(error));
```
**Correct usage:**
```js
    SwaggerClient('https://petstore.swagger.io/v2/swagger.json')
      .then(client => {
        return client.execute({
          operationId: "findPetsByStatus",
          status: 'available',
        })
      })
     .catch(error => console.error(error));
```


For more information about how Promise chaining work, have a look at this [article](https://javascript.info/promise-chaining).

@kavisuresh It would really help if you'd paste here the code fragment that doesn't work for you. Then we would be able to say with certainty what is wrong. Please along with that provide a version of swagger-js library you're using.
