### ISSUE TITLE
Breaking 2.x->3.x content type behavior?

### ISSUE THREAD

**Issue by djMax** [swagger-api/swagger-js#1272]
Our 3.x API clients fail because seemingly no content type headers are sent for JSON calls. This used to work fine. Did something change in regards to this scenario?

**Comment by shockey** [comment]
This should work fine if your API document defines the media types correctly. 

Can you provide an example definition and Swagger-Client usage pattern that I can use to observe this?

**Comment by djMax** [comment]
That's exactly the behavior change. One of the services we use did not specify a "consumes" value, and the libray no longer defaults. I assume this is because of the switch from super agent. (Why are we using 0.0.8 of the fetch module when there's a 2.0?)

**Comment by webron** [comment]
@djMax iirc, we did make the change that it no longer defaults - it is a more 'correct' behavior. For OAS3 definitions it's not really an issue because you cannot not set a media type for requests (or responses). 

@shockey is there a way, not necessarily through configuration but through code, to make the client assume a default media type if one is not provided? That should be a reasonable workaround for users of the library with the changed behavior, as they can't always modify their API definitions to satisfy this requirement.

**Comment by shockey** [comment]
@webron that would be possible - should we assume `application/json` if we otherwise have no idea what Content-Type to send?

**Comment by webron** [comment]
Not something we should assume, but the users. If we provide with a code snippet they can add for example to the index.html it's enough. Not looking to add it to the core functionality.

**Comment by shockey** [comment]
Hmm... One should be able to achieve this with a request interceptor:

```js
Swagger({
  url: "http://petstore.swagger.io/v2/swagger.json",
  requestInterceptor: req => {
    if(req.body && !req.headers["Content-Type"]) {
      req.headers["Content-Type"] = "application/json"
    }
  }
})
```

**Comment by webron** [comment]
Then I believe we can add that description to the migration guide doc and close it as such.
