### ISSUE TITLE
Outdated build targets in .travis.yml

### ISSUE THREAD

**Issue by sebs** [swagger-api/swagger-js#1302]
I would like to propse a update to the used node js versions. 

Here is what travis supports: 

node latest stable Node.js release
iojs latest stable io.js release
lts/* latest LTS Node.js release
8 latest 8.x release
7 latest 7.x release
6 latest 6.x release
5 latest 5.x release
4 latest 4.x release

With the very exact versions (node 4.7 y?) travis might silently skip to another minor updated version anyway. So all in all I would love to see more builds for more systems. Especially since my whole toolchain is more "modern node.js" than what is used here. 

Can you update this to a bunch ore build targets please?

**Comment by shockey** [comment]
Hi @sebs! I totally agree, our CI targets need to be updated. While I would love to test every version, Travis only lets us run so many containers at once... so we should be careful to avoid adding so many that every build causes a job queue to form.

In #1275, I dropped v4 (it's EOL in less than a month), added v6, and started testing against the latest LTS.

I omitted the latest version (`- "node"` in travis config) for now, because v10 was breaking [literally every single HTTP test](https://travis-ci.org/swagger-api/swagger-js/jobs/374261036).

**Comment by char0n** [comment]
We're currently using Github Actions and running our Jobs on node version 10, 12 and 14. We're building our build artifacts also for node@8, so we have a special dedicated job that tests build artifacts on node@8, even though it's no longer supported. We're also testing our browser build artifacts in browser environment to make sure they are build just fine. You can learn more about it [here](https://github.com/swagger-api/swagger-js/runs/825832933).

I think we can close this issue, as what has been reported is already rectified.

@sebs thanks!
