### ISSUE TITLE
Please add a reason why to choose swagger-js over swagger-code-gen

### ISSUE THREAD

**Issue by emreavsar** [swagger-api/swagger-js#1345]
Simple question, which I couldn't find an answer for in the readme (and internet):

**Why should one prefer using this library (swagger-js) over using the swagger-code-gen**

I see the following discussion points:

**swagger-js:**
- no code generation needed
- works out of the box (more or less)

**swagger-code-gen:**
- needs additional code generation
- has some problems with generated files
- stronger typing (at least operations are encapsulated as own methods)

Is there I've forgot here to add? 

thanks!

**Comment by SerCarciofini** [comment]
I might be wrong, but i think swagger-client, running in node environment, uses to fetch the specification each time. It's a waste of resources.
On the other side with swagger-code-gen you generate your middleware, integrate it and that's it, much faster in a production environment.

**Comment by emreavsar** [comment]
That was what inwas thinking, but it is not clearly written anywhere and in
the codegen repo there is a „what about javascript“ section which leads to
this repo.

**Comment by shockey** [comment]
> I might be wrong, but i think swagger-client, running in node environment, uses to fetch the specification each time.

@SerCarciofini, this is correct. If you load your definition through a URL, it will be fetched every time your application runs.

---

> Why should one prefer using this library (swagger-js) over using the swagger-code-gen

The projects are, indeed, built to solve similar but different problems. The main difference is that Swagger-Codegen creates an interface from your definition at build time, and Swagger Client creates an interface at run time.

Reasons to choose Swagger Client:
- You're working with an OpenAPI-enabled service that changes frequently (Swagger Client will automatically keep up with changes, since it grabs the current OpenAPI document each time your application loads)
- You're building an application that allows users to interface with their _own_ services (this is why Swagger UI makes heavy usage of Swagger Client)
- You prefer simplicity over performance
- You need support for more OpenAPI 3.0 features (my understanding is that Swagger Client is further along with the more esoteric parts of 3.0 than Codegen)

Reasons to choose Swagger Codegen:
- You're working with specific services that don't change often (since you'll need to generate a new client, probably manually, each time the service you're using changes)
- Performance is a priority, even at the cost of having devs regenerate code manually from time to time

**Comment by emreavsar** [comment]
This should be summarized in [README.md](https://github.com/swagger-api/swagger-codegen/blob/master/README.md) in code-gen.
