### ISSUE TITLE
userFetch ignored when resolving swagger spec via constructor method

### ISSUE THREAD

**Issue by chrismatheson** [swagger-api/swagger-js#1417]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Node.js v10.0.0
 - Method of installation: npm
 - Swagger-Client version:  3.8.22
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
during test i would like to override the swagger library (my single point of I/O to the outside world) using the userFetch option.

however when my code initialises the Swagger client, the resolve action is triggered which does *not* (as far as i can tell) use the `userFetch` provided in options.

### To reproduce...

new Swagger({
    url: 'http://localhost:8000/schema',
    userFetch() { return new Response() }
});

and see a network error for cannot connect to localhost 

### Expected behavior
userFetch is called with the URL given to the Swagger constructor

**Comment by char0n** [comment]
Hi @chrismatheson,

Yes in order to satisfy your requirement for testing, `userFetch` will not help in this case. Let me explain it on following example.

```js
import SwaggerClient from 'swagger-client';

const client = await new SwaggerClient({
  url: 'https://petstore.swagger.io/v2/swagger.json',
});

const response = await client.apis.user.getUserByName({ username: 'username' });
```
SwaggerClient does two things here:

1. It executes [OpenApi Definition Resolver](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/openapi-definition-resolver.md) downloads the `swagger.json` and resolve all [JSON references](http://niem.github.io/json/reference/json-schema/references/) inside it. How the document is downloaded and references resolved is controlled via [http override](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/openapi-definition-resolver.md#options).

```js
import SwaggerClient from 'swagger-client';

const client = await new SwaggerClient({
  url: 'https://petstore.swagger.io/v2/swagger.json',
  http: (url, request) => Promise.resolve(...mocking downloading and resolving the swagger.json document ...),
});

const response = await client.apis.user.getUserByName({ username: 'username' });
```

2. The last line in my code fragment represents will use overriden [HTTP Client](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md) to execute `getUserByName` operation from petstore swagger.json document.


Now when does one use `userFetch`? This override should exclusively be used when using [Tags Interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md) or [Try It Out Executor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md) and is documented in [HTTP Client](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md).

```js
new SwaggerClient({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  userFetch: (url, request) => Promise.resolve(new Response()),
}).then((client) =>
  client.apis.user.getUserByName(
    { username: 'username' },
    {
      requestInterceptor: interfaceLevelRequestInterceptor,
    }
  )
);
```
Now all the operation done with resolved client will use `userFetch` override.

What is the difference between `http` and `userFetch`? The answer should be apparent from [HTTP Client](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md) documentation. `http` is an actual instance of HTTP Client and uses `userFetch`, runs interceptors and serializes headers and response bodies. `userFetch` is custom asynchronous fetch function that accepts two arguments: the url and the Request object and must return a Response object

Hope it helped.
