### ISSUE TITLE
[OpenAPI 3.0]: Fileupload with multiple files using multipart/form-data

### ISSUE THREAD

**Issue by timaschew** [swagger-api/swagger-js#1426]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Node.js v8
 - Method of installation: npm
 - Swagger-Client version: 3.8.23
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
paths:
  /services:
    post:
      description: Add a new service
      operationId: addService
      requestBody:
        $ref: '#/components/requestBodies/Service'

  requestBodies:
    Service:
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - manifest
              - configuration
            properties:
              manifest:
                type: string
                format: binary
                description: Defines the service and data interfaces. In YAML format.
              configuration:
                type: string
                format: binary
                description: Configuration file. In YAML format.
          encoding:
            manifest:
              contentType: text/yaml; charset=utf-8
            configuration:
              contentType: text/yaml; charset=utf-8
```

Swagger-Client usage:
```js
const fs = require('fs')
const path = require('path')
const Swagger = require('swagger-client')
const yaml = require('js-yaml')

const content = fs.readFileSync(path.join(process.cwd(), 'openapi-spec.yaml'), 'utf8')
const options = {
	spec: yaml.safeLoad(content)
}

const file1 = fs.readFileSync(path.join(process.cwd(), 'manifest.yml'), 'utf8')
const file2 = fs.readFileSync(path.join(process.cwd(), 'config.yml'), 'utf8')

new Swagger(options).then(client => {
  return client.apis.default.addService({
    manifest: file1,
    configuration: file2
  })
})
```

### Actual Output
This is the output of the server
```
rg.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is javax.servlet.ServletException: org.apache.tomcat.util.http.fileupload.FileUploadBase$InvalidContentTypeException: the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is null
```

### Expected Output
Works without any error.  
The server works fine when using **Try it out** in the Swagger editor.

**Comment by Lukas-Kullmann** [comment]
I'm kind of the same issue. For me, the backend server complains, that a required request part is not present.

I debugged it to a point where I identified [this line](https://github.com/swagger-api/swagger-js/blob/master/src/execute/oas3/build-request.js#L74) as the issue.

It just does not support file streams.
Converting the stream to a buffer (as one might think works due to [line 71](https://github.com/swagger-api/swagger-js/blob/master/src/execute/oas3/build-request.js#L71)) does also not work since swagger-client uses the buffer package and does not rely on the built-in buffer.

This is also the reason, it works in the browser. There the upload is a file and will not be stringified.

So in conlusion: It would be nice if a support for node file upload via streams would be possible.

**Comment by shockey** [comment]
Hi @timaschew, it appears you're passing your request body properties as parameters, which won't work.

Try this:

```js
  return client.apis.default.addService({}, {
    requestBody: {
      manifest: file1,
      configuration: file2
    }
  })
```

[Relevant docs are here in the README](https://github.com/swagger-api/swagger-js/blob/d1960ebfb6e4206af8a5d6a2ba911899b372456d/README.md#openapi-30).

---

@Lukas-Kullmann, I don't think stream conversion is a factor here, since OP is using `readFileSync` with an encoding specified, [which should return a string](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options). Sounds like a valid problem though -- feel free to open a new issue for that.

**Comment by PiotrNestor** [comment]
We've got the same problem where a request body is a file provided with 'fs.readFileSync'.
Do you know when this issue can be fixed?
Thanks!

**Comment by neidhart-orlich-bt** [comment]
I think the PR I just created might fix this issue. However, I am a java developer and don't know much about node.js so I couldn't test the changes yet. If somebody would be so kind as to help me set up an environment where I could test the changes (or do that for me) I would be very grateful :)

**Comment by tim-lai** [comment]
@timaschew Thanks for reporting this issue. PR#1527 should resolve it.
