### ISSUE TITLE
Not using custom http

### ISSUE THREAD

**Issue by shayantabrizi** [swagger-api/swagger-js#1479]
At [here](https://github.com/swagger-api/swagger-js/blob/ba069cb9f61d3b4d0095e84af4b2b613cb8ac9a1/src/index.js#L69) it seems to me that http option is not passed and thus if I set Swagger.http = myCustomHttp or Swagger.prototype.http=myCustomHttp they are ignored.

**Comment by char0n** [comment]
@shayantabrizi yes, you're absolutely right. This issue is very similar with #1476. Current workaround would be override the subclass the `SwaggerClient` class or to use `SwaggerClient.execute` static method. 

More context in [this comment](https://github.com/swagger-api/swagger-js/issues/1476#issuecomment-621108849).

**Comment by char0n** [comment]
Attached PR fixing this problem: https://github.com/swagger-api/swagger-js/pull/1560

Along with that, we've introduced `options` parameter for instance `resolve` method which should allow additional explicit overrides.

**Comment by char0n** [comment]
Will be released in swagger-client@3.10.8
