### ISSUE TITLE
Publish source map to npm

### ISSUE THREAD

**Issue by RazerM** [swagger-api/swagger-js#1482]
`dist/index.js` contains `//# sourceMappingURL=index.js.map` at the bottom, but this file isn't included in `files`:

https://github.com/swagger-api/swagger-js/blob/ba069cb9f61d3b4d0095e84af4b2b613cb8ac9a1/package.json#L16-L22

**Comment by char0n** [comment]
Hi @RazerM,

We don't include source map into npm distribution package because it would double the npm distribution package size. 

But let me understand your problem better. Is it the problem that

1.)  we don't distribute source maps at all 
2.)  or that we reference the non-existing source maps from bundles?

**Comment by char0n** [comment]
Closing in favor of #1542. We will not be distributing source maps in future, unless there is a very good reason to do it.

**Comment by char0n** [comment]
@RazerM I've reviewed my decision and we will include sourcemap into npm distribution for browser build artifact. THank you for pointing this out! https://github.com/swagger-api/swagger-js/pull/1581
