### ISSUE TITLE
Support an option to allow special characters in operationId

### ISSUE THREAD

**Issue by dannyongnintex** [swagger-api/swagger-js#1498]
When operationId contains special characters, it escapes them by replacing special characters with underscores.
https://github.com/swagger-api/swagger-js/blob/f8fccb45107c76c0dd45d9d0e4583087b97ef6b3/src/helpers.js#L28

Can we have an option to skip escaping special characters in operation IDs?

Swagger specification for v2.0 doesn't mention that special characters are not allowed in operationIds. So we hope to use the operationId defined in the swagger file.

https://swagger.io/docs/specification/2-0/paths-and-operations/

**Comment by char0n** [comment]
I guess we're talking specifically about [tags interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md). As tags interface is opinionated JavaScript representation of OAS definition, we've chosen to escape special characters in `operationsId` so that we can generate valid JavaScript function name and be able to call it as a function.

You can still bypass Tags Interface use [TryItOut Executor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md) where you can refer to `operationId` with original name.

```js
import SwaggerClient from 'swagger-client';

SwaggerClient.execute({
  spec: pojoDefinition,
  operationId: '^%$',
   parameters: { q: 'search string' }, 
}); // => Promise.<Response>
```
