### ISSUE TITLE
look at parser reuse

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#152]
Perhaps we can work with https://github.com/BigstickCarpet/swagger-parser or https://github.com/apigee-127/swagger-tools to use a single swagger parser?  Not sure what the effort is like to get them browser-friendly (and IE 8 compatible for that matter).

/cc: @BigstickCarpet @whitlockjc

**Comment by whitlockjc** [comment]
I personally think both projects suggested will not do much for what I think a parser should do.  Both swagger-parser and swagger-tools seem to focus on document validation, reference dereferencing, etc.  While those are useful features, my opinion of a parser would do more than that.

What I'd like to see is a complete Swagger object model, something that more closely matches the terminology of the Swagger specification and is less of a port from previous Swagger specifications, and an API around constructing/deconstructing Swagger structures/documents.  _(I don't think either of the projects suggested do this.)_  There should also be some value add APIs, like validation and reference dereferencing and document/structure traversal, etc.  _(This is where I think swagger-parser and swagger-tools could contribute seeing as both projects do all of this already.)_

In the end, this is just my opinion.  I think the reason there are so many projects that do the same thing and solve the same problem in the Swagger space is because there is no _official_ means to do these things.  I think if there was a Swagger API and object model, it would make building Swagger tooling and integrations much, much easier and without N different implementations of the same thing.

**Comment by fehguy** [comment]
I think you're right and this won't make much sense for this project.
