### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by vvanpo** [swagger-api/swagger-js#1633]
The `browserslist` configuration used to build this project already resolves to IE11, and all the necessary polyfills are injected by `@babel/plugin-transform-runtime`. However, the `cross-fetch` dependency does not ship with a `Promise` polyfill: https://github.com/lquixada/cross-fetch#usage (see the warning at the bottom of the usage documentation).

As a result, the browser bundle contains references to both the "pure" `Promise` ponyfill supplied by `@babel/runtime-corejs2`, and native `new Promise()` calls made by `cross-fetch`.

Could we either document that `swagger-js` will only work in an environment supporting promises, or ensure that the usages in `cross-fetch` are polyfilled? The latter isn't ideal, because it would require choosing between:
1. Bundling `cross-fetch` inside `swagger-js` (i.e. moving it to `devDependencies`), and letting `@babel/plugin-transform-runtime` transform its `Promise` calls.
2. Keeping `cross-fetch` as a dependency, but adding the `Promise` _polyfill_ (i.e. global, what you get when you set `useBuiltIns: "usage"` in `@babel/preset-env`) instead of the ponyfill provided by `@babel/runtime-corejs2`.
3. A hybrid, where the ES module build still has a dependency on an external `cross-fetch` (and is documented as requiring a global polyfill), but the bundled browser build properly ponyfills its calls to `Promise`.

**Comment by char0n** [comment]
Hi @vvanpo,

Thanks for your analysis. 

Option 1 with slight modification seems like most viable option to me:

> Bundling cross-fetch inside swagger-js (i.e. moving it to devDependencies), and letting @babel/plugin-transform-runtime transform its Promise calls.

**Modification**

I'm not sure I understand why to move it to `devDependencies.` What we need to do is to allow `@babel/plugin-transform-runtime` to transform cross-fetch a in't promise calls (as you say). But `cross-fetch` needs to stay a runtime dependency for other fragments we expose. You can read more about out build artifacts here: https://github.com/swagger-api/swagger-js/issues/1542

**Reasoning**

We officially say that we don't support IE in our documentation by stating:
> swagger-client works in the latest versions of Chrome, Safari, Firefox, and Edge.
But the problem you describe may not affect only  IE, but other browsers too. So in order to be consistent our browser bundle should work an environment we build it against. Other thing is we don't want any polyfills to leak to a global scope of the browser. 

Would you be able to play with this and issue a PR?
