### ISSUE TITLE
client.http({...}) doesn't use requestInterceptor set up on the client.

### ISSUE THREAD

**Issue by tclayson** [swagger-api/swagger-js#1707]
I am setting up a Swagger client using the following code:

```javascript
const client = Swagger("http://some.url/swagger.json", {
    requestInterceptor: request => {
        request.headers.Authorization = "Bearer " + auth_token;
        return request;
    }
});
```

There is an undocumented endpoint that I want to reach, using the same Swagger client, but without using `client.api.Endpoint` (because this endpoint isn't in the swagger spec).

I thought I could use the `http-client` to do this, and I noticed that you can use the `http-client` of the Swagger client by doing the following:

```javascript
let response = await client.http({ url: "http://some.url/api/undocumented_endpoint" });
```

This works, but it doesn't use the request interceptor set up on the Swagger client (in this instance I am getting an error back from the API stating that there is no authorization header).

I don't particularly want to have to maintain my request interceptors in multiple places, so is there any way that I can use the client's request interceptor on this `http-client` request?

Many thanks
Thomas

**Comment by char0n** [comment]
Hi @tclayson,
```js
let response = await client.http({ url: "http://some.url/api/undocumented_endpoint" });
```
In this case `client.http` is equivalent to calling `SwaggerClient.http`. This means that calling `client.http` doesn't make this call context aware; it has been designed in this way, it's not a bug. In order to solve your problem, you have two options

1. **Passing `requestInterceptor` explicitly** 

```js
let response = await client.http({ url: "http://some.url/api/undocumented_endpoint", requestInterceptor: client.requestInterceptor });
```

2. **Extending SwaggerClient**

Another option (if this case is common for you) is to extend SwaggerClient and pass a `requestInterceptor` to the call.

**Comment by tclayson** [comment]
Thanks! @char0n 

Your option 1 works fine, and isn't too difficult to implement. Exactly what I needed, thank you!

Thomas

**Comment by char0n** [comment]
Glad to be of help
