### ISSUE TITLE
evaluate deprecation of test/bugs structure

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1725]
### Content & configuration

### Is your feature request related to a problem?

The tests in `/test/bugs` might be able to be incorporated into their related functional unit tests. This may help keep the unit tests more organized and reduce fragmentation of related function. If we want to keep track of bugs that were fixed, we should include the issue number in the test description.

### Describe the solution you'd like

I'm open to both current and consolidated options.

### Describe alternatives you've considered

There may be other tooling impact/expectation of tracking by bug ticket number.

### Additional context

 discussion from PR #1720

**Comment by tim-lai** [comment]
char0n
> Is there a reason why are we using this convention of creating a test file numbered as the bug number instead of incorporating the test directly into subtree-resolver tests?
IMHO it fragments the tests and brings no additional value. It would be more sensible to create test directly in test/subtree-resolver.js and create minimal specification for the test that satisfy the code change (the same way as existing tests does it).


tim-lai
> Just following existing project examples. fyi, swagger-ui and swagger-editor do this too.
Also, the test/subtree-resolver currently only runs a single test due to existence of a test.only(). There appears to be two breaking tests that are currently skipped.

char0n
> My questions are more: Why we're doing this? Do we know why this convention exists and what are the conditions to activate it? How do we benefit from it?
Damn...let's fix it and run all tests except the ones that don't pass ;]

**Comment by char0n** [comment]
### Proposed solution

**Always integrate new tests** in modules/places where they belong. Choose specific
test description that properly describe the test case/suite. If needed associate the 
test case with code comment containing the particular URL to GitHub issue.

**In special cases** when it's too hard to come up with specific test description,
due to the fact that it's complex to describe the problem in couple of words (one sentence), issue number can be 
used as test description, file name or fixture name as long as the test is placed in module where it
should belong.

**Work progressively** on integrating existing tests files from `test/bugs/` directory into appropriate 
test suites to eliminate the test fragmentation.
