### ISSUE TITLE
Getting response from rejected Promise

### ISSUE THREAD

**Issue by zim32** [swagger-api/swagger-js#1753]
### Q&A (please complete the following information)
 - OS: Linux
 - Environment:Chrome 84
 - Method of installation: npm
 - Swagger-Client version: 3.11.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
I am using Tag interface to make query and I want to catch 400 errors from my server and process them. But I can not get Response from rejected promise

Here is my code:

```
let response = this.$api.swagger.apis['Users']['registerUser']({}, {
    requestBody: postData
});

response
    .then(response => console.log('OK', response))
    .catch(err => console.log('GOT ERROR: ', err));
```

My server returns 400 status code and some payload JSON. But in console I see only plain string

**GOT ERROR:  Error: Bad Request**

How to get response?

**Comment by char0n** [comment]
Hi @zim32,

Here is a [documentation describing how swagger-client handles errors](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#errors). As you can see from the documentation, error object passed to your callback has additional properties of `statusCode` and `response` which holds a reference to the original response returned by the server.

**Comment by zim32** [comment]
But I got String not object. In dev console I have just string. string with text Error: Bad Request

**Comment by char0n** [comment]
We'd need a minimal POC with running server (that we'll run requests against) and minimal OpenAPI definition file (that swagger-client will consume) to reproduce your situation and detect where the problem is. Would you be able to provide one? The information provided in description of this issue are not sufficient to provide any additional help. 

I've suspect this the code [responsive for providing the error](https://github.com/swagger-api/swagger-js/blob/master/src/http.js#L72) may give you trouble but we need the above mentioned POC to be able to reproduce the problem and fix it.

**Comment by zim32** [comment]
Ok I will try.
