### ISSUE TITLE
Why use globals?

### ISSUE THREAD

**Issue by MattiSG** [swagger-api/swagger-js#178]
This library seems to be relying on a large amount of globals to function. This is surprising, as leaking state-holding variables in the global namespace is most often considered [bad practice](http://www.w3.org/wiki/JavaScript_best_practices#Avoid_globals), for it leads to potential conflicts with other libraries and decreased maintainability.

However, this practice seems absolutely conscious and voluntary in this project, as these variables are prefixed with `window.` to expose them globally on the browser (potentially through an intermediate variable for Node compatibility).

As this practice makes me extremely wary of including the library as it is, I would like to know what is the rationale for exposing so many globals (and requesting clients to do so too).

**Comment by MattiSG** [comment]
@fehguy Does adding the “Feature” tag mean removing globals is an expected feature?

**Comment by fehguy** [comment]
Yes, we are looking at moving them out in the 2.1 release

**Comment by whitlockjc** [comment]
https://github.com/swagger-api/swagger-js/pull/279 should remove all globals other than `SwaggerClient` in the browser.  `authorizations` is now an instance variable for `SwaggerClient` named `clientAuthorizations`.  `models` is now an instance variable for `SwaggerClient` named `models`.  The `addModel` function was removed as it was only for testing and the following constructors were removed because they too were only for testing: `Model`, `Operation` and `Resolver`.

The following constructors are exposed as properties on the `SwaggerClient` constructor and can be used as they were before: `ApiKeyAuthorization`, `CookieAuthorization` and `PasswordAuthorization`.  `SwaggerApi` and `SwaggerClient` are also exposed as properties on the `SwaggerClient` constructor for backward compatibility.  Usage of these constructors will result in a deprecation warning.

**Comment by MattiSG** [comment]
Great!! Will test ASAP.

**Comment by whitlockjc** [comment]
I just merged #279 so the only global now is `SwaggerClient`.
