### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by elInfidel** [swagger-api/swagger-js#1969]
Hey,

I'd be interested in contributing typescript types to this project, I use it extensively and would prefer not to rely on my own declared module. Is there a specific set of tasks left to achieve this goal?

I've never contributed types to a third party library before so my understanding of the process is fuzzy.

Regards

**Comment by char0n** [comment]
Hi @elInfidel,

Again I say give it a shot ;] Let me describe the ideal outcome of your efforts. I'll demonstrate ideal outcome on a example library called [ramda-adjunct](https://github.com/char0n/ramda-adjunct) where I participated in similar effort.

#### Define typings

Create a [types directory](https://github.com/char0n/ramda-adjunct/tree/master/types) where you implement the typings for swagger-client public API.

#### Create tests for typings

Create [tests for typings](url). Usually running the typings is enough but having tests for them would be great. For actuall testing library called [dtslint](https://github.com/microsoft/dtslint) can be used.

#### Map the typings

Next we need to [map the typings to package.json](https://github.com/char0n/ramda-adjunct/blob/master/package.json#L64) in order to tooling to recognize that swagger-client has typings.

If you'll have any additional questions just mention me in comments and I'll response ASAP.

**Comment by elInfidel** [comment]
Thanks,

I'll review this information tonight and see about getting started.

Regards

**Comment by elInfidel** [comment]
Hey @char0n ,

Just an update. I've begun slowly chipping away at the types in the following branch.

https://github.com/elInfidel/swagger-js/tree/add-typescript-types

Feel free to leave any comments. I'm not going particularly fast so there might not be much to comment on yet at this point.

**Comment by char0n** [comment]
Seems like a good start!

**Comment by char0n** [comment]
@elInfidel how are we looking here. Do you still have time to push through with this?

**Comment by elInfidel** [comment]
Hey @char0n Deepest apologies for this. Admittedly I underestimated the work involved, as many do. I'd rather return it so someone else can get a shot. I don't have enough time to do this feature the justice it deserves.

**Comment by char0n** [comment]
@elInfidel no worries at all. This requires significant effort and I fully understand you have other priorities.

Closing this for now.
