### ISSUE TITLE
Handle nested object parameters with dot notation in buildrequest for try it

### ISSUE THREAD

**Issue by robertwjames0** [swagger-api/swagger-js#2326]
### Content & configuration

 Swagger/OpenAPI definition:
 ```yaml
/v1/Example:
    get:
      tags:
        - Example
      summary: example request
      parameters:
        - name: FirstObject.Example
          in: query
          schema:
            type: string
        - name: SecondObject.Example
          in: query
          schema:
            type: string
 ```

 Swagger-Client usage:
 Using 'try it' on redocly portal

### Is your feature request related to a problem?
We have two main object parameters for most of our requests. We have set up our openapi spec to include the object name in those parameters as above. When using 'try it' the parameters are not set as they are stored as 
 ```[FirstObject, SecondObject] ```
 but the try it function looks for 'FirstObject.Example' instead of FirstObject. 

### Describe the solution you'd like

Here's a patch for 'swagger-js/src/execute/index.js', to replace the current behaviour with one that is aware of a.b parameters
 ```
191c191,204
<     value = parameter && parameter.name && parameters[parameter.name];
---
>     if(parameter && parameter.name){
>         if(parameter.name.includes('.')){
>           var names = parameter.name.split('.');
>           value = parameters[names[0]];
>           for(var i = 1; i < names.length; i++){
>             if(!value){
>               break;
>             }
>             value = value[names[i]]
>           }
>         }else{
>           value = parameters[parameter.name];
>         }
>     }

 ```

### Describe alternatives you've considered
I have tried using hooks to update the parameters but the problem happens before the hook is run, so if a parameter is required the hook will not be run and we get an error message. I have tried overriding this function in a few different ways but they don't work on redocly's servers due to how they reference libraries.

**Comment by char0n** [comment]
Hi @robertwjames0,

IMHO your patch will introduce breaking change behavior for parameters that contains `.` for everybody else as it will consider dot notation as parameter object path instead of simple name. 

By `hooks` you mean requests interceptors? If yes, then you're right, it's no use, because the request was already build when interceptor intercepts it.

Please have a look at [HTTP client for OAS operations](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client-for-oas-operations.md). I've added additional property called `parameterBuilders` that will do exactly what you want. Description of the property contains two links for implementation of parameter builders for OAS 2.x and OAS 3.0.x - it will help you to start with your own implementation.
