### ISSUE TITLE
Convert swagger-client to TypeScript

### ISSUE THREAD

**Issue by xiaoxiangmoe** [swagger-api/swagger-js#2916]
APIDom is using TypeScript now.
Should we change source code for this project into TypeScript?
I'll happy to help for this job.

**Comment by xiaoxiangmoe** [comment]
@char0n

**Comment by char0n** [comment]
Hi @xiaoxiangmoe,

> APIDom is using TypeScript now

Yes, that's true, but the quality of TypeScript there is low, as during implementations I've prioritized getting the complex algorithms right, instead of the types. 

> Should we change source code for this project into TypeScript? 

IMHO I'd postpone for some time. Including TypeScript in project has implications and add additional overhead.

> I'll happy to help for this job.

If you want to help now, what we can do now is to create typings `*.d.ts` file for this project and distribute it with the npm package distribution, but leave the code JavaScript based.


Another thing, what we need help is to increase TypeScript quality in ApiDOM monorepo. What we need first is quality typings for https://github.com/refractproject/minim which forms the very base of ApiDOM.

**Comment by char0n** [comment]
I'm closing this for now as converting this codebase to TypeScript is not a priority currently. 

As mentioned, PRs with `*.d.ts` (typings file) are welcome.
