### ISSUE TITLE
Switching from node 16 to 18 changes TLS implementation of request on spec

### ISSUE THREAD

**Issue by dchicchon** [swagger-api/swagger-js#3163]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: node 18
 - Method of installation: npm
 - Swagger-Client version: latest
 - Swagger/OpenAPI version: 3.1

### Content & configuration
N/A

Swagger/OpenAPI definition:
N/A

Swagger-Client usage:
```js
SwaggerClient({
     spec: modelSpec,
      authorizations: authentication,
      requestInterceptor: req => {
        req.agent = new https.Agent({
               requestCert: true,
               rejectUnauthorized: false,
        })
      },
})
```

### How can we help?
When going to from node 16 to node 18 I noticed that the request implementation uses node's native `fetch`. Because of this, the `requestInterceptor` is no longer able to pass in TLS options on an agent. This results in a breaking change for our usage of `swagger-client`

**Comment by char0n** [comment]
Hi @dchicchon,

What you're looking for is [userFetch option](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#custom-fetch). If you're using features specific to certain `fetch` implementation that are not part of the [official Fetch Standard](https://fetch.spec.whatwg.org/), `userFetch` is a way to go as it allows to to bind swagger-client to your preferred fetch implementation.

```js
import nodeFetch from 'node-fetch';

SwaggerClient({
     spec: modelSpec,
      authorizations: authentication,
      requestInterceptor: req => {
        req.userFetch = nodeFetch;

        req.agent = new https.Agent({
          requestCert: true,
          rejectUnauthorized: false,
        })
   
        return req;
      },
});
```
---

Refs #3032

**Comment by tomchiverton** [comment]
Are you saying unless userFetch is set , agent setting is now ignored?

**Comment by char0n** [comment]
@tomchiverton no, that's not what I'm saying.

Please read the following section of main readme: https://github.com/swagger-api/swagger-js#nodejs

![image](https://github.com/swagger-api/swagger-js/assets/193286/a2045cee-0ea8-4d04-bed4-c3824de965d0)

Depending on the Node.js version we're using different fetch API implementation. We're only using features from all of these implementations that are part of fetch API spec. If you use some specific obscure features from a specific fetch API implementation, you'll have to use `userFetch` to always force using specific fetch API implementation.  If you're using Node.js >=12.20.0 <16.8, swagger-client uses node-fetch@3 automatically, which supports the agent. For Node.js >= 16.8, in order to keep using `node-fetch@3` and have ability to set agent, `userFetch` is a way to go. 

If swagger-client minimal supported Node.js version is >18, swagger-client will only use native fetch API implementation, either supported from Node.js or Browser.
