### ISSUE TITLE
sample on Github Readme page is not working

### ISSUE THREAD

**Issue by prashanthmadi** [swagger-api/swagger-js#439]
Hi,

I was trying to execute the code on Github readme page but i always receive obj value as empty for petstore sample. looks like i'm missing something very simple. Any help would be appreciable. Thanks!

when i try same url on browser. it gives me values 
url : http://petstore.swagger.io/v2/pet/7
Value : {"id":7,"category":{"id":4,"name":"Lions"},"name":"Lion 1","photoUrls":["url1","url2"],"tags":[{"id":1,"name":"tag1"},{"id":2,"name":"tag2"}],"status":"not available"}

```js
var client = require("swagger-client")

        var swagger = new client({
            url: 'http://petstore.swagger.io/v2/swagger.json',
            success: function() {
               swagger.pet.getPetById({petId:7},function(data){
                   res.send(JSON.stringify(data));
               });
            }
        });
```

{"url":"http://petstore.swagger.io/v2/pet/7","method":"GET","headers":{"access-control-allow-origin":"*","access-control-allow-methods":"GET, POST, DELETE, PUT","access-control-allow-headers":"Content-Type, api_key, Authorization","content-type":"application/xml","connection":"close","server":"Jetty(9.2.7.v20150116)"},

**"obj":{},**

"status":200}

**Comment by ponelat** [comment]
For starters, since no Accept type is requested(you can ask the server for the format of the response...xml/json/etc) it defaults to the first one it can find... which in this case is application/xml. So obj will be empty as we don't parse xml into the system.

To help in this particular case, just request application/json and you should see a populated obj...

```javascript
var swagger = new client({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  success: function() {
    swagger.pet.getPetById({petId:7},{responseContentType: 'application/json'},function(pet){
      console.log('pet', pet.obj);
    });
  }
})

```
*BUT* I don't see a statusText when using application/xml, which should hold the response xml, so I will be looking into this.

@webron there is a bug with the node.js client, works fine in a browser (tested minimal setup)... application/xml doesn't populate the .data _or_ .statusText properties. New issue? Probably update the readme as well, 'cause the above caught me out as well at some point. OR we can try to default to application/json *if* it is available (ie: it's in produces)

**Comment by webron** [comment]
@ponelat - yes to creating an issue, yes to update the README. I wouldn't default to application/json just yet, but you can create an issue suggesting that as well.

**Comment by ponelat** [comment]
@prashanthmadi let us know if you came right. We've since updated the README.md

**Comment by prashanthmadi** [comment]
Thanks @ponelat, your sample code helped me in fixing the issue.
