### ISSUE TITLE
Problem with body parameter

### ISSUE THREAD

**Issue by skyhit** [swagger-api/swagger-js#598]
I have the following definition like 
```
...
       {
        "type": "string",
        "paramType": "body",
        "name": "code",
        "description": "the new formula code",
        "required": true,
        "allowMultiple": false
       },
```

the swagger ui interpret it as `body`, instead of `name`
![image](https://cloud.githubusercontent.com/assets/58106/10684701/0361f12a-7983-11e5-970e-e7990dc5beb8.png)

same inside the code call, I have to use `body`, instead of `name`

**Comment by webron** [comment]
From the looks of it, you're using an older version of Swagger (that is, something before 2.0). In those versions, the name of `body` parameters *had* to be "body". Since swagger-ui now converts older versions to 2.0, and still follows the older rules, it will automatically assign the name "body" to those parameters.

If it's important for you to name them differently (it doesn't affect functionality, only documentation) then you'd have to update to the latest version of Swagger.

**Comment by skyhit** [comment]
@webron actually, looks to me that the name of the body parameter is not required, when using the new version of swagger client, it has to be "body", not the specific name.

**Comment by webron** [comment]
If you use an older version of the *spec*, it may just assume the name "body".

**Comment by fehguy** [comment]
@webron is correct.  For pre 2.0 specs, it was assumed the name was `body` and not required.
