### ISSUE TITLE
model classes vs http://editor.swagger.io/

### ISSUE THREAD

**Issue by mbana** [swagger-api/swagger-js#838]
hi,

how does one access the models that client constructs?
i've noticed that i can export a client via http://editor.swagger.io/, that comes along with the model definitions.
basically, some sort of "static typing" would be great...

thanks,

**Comment by fehguy** [comment]
You can get back to model definitions like such:

`client.models['yourModelName'].definition`

Will return to you the JSON schema representation of the model.

**Comment by mbana** [comment]
Please reopen this.

Why doesn't the client API return these models in the callback instead of a plain JSON object? `res.obj` is a plain JSON object.

**Comment by fehguy** [comment]
Because, `res.obj` is the parsed version of your _response payload_, not the payload definition.  It doesn't make sense to be in that object.

**Comment by mbana** [comment]
I think it does. It makes it clear what the actual response is instead of a
plain js file. This is more clear.

**Comment by fehguy** [comment]
You mean, instead of the actual values that your server sends, you'd rather have the definition of what it's supposed to send?  I think you're mixed up, let me clarify.

* If the response is parseable, as either an XML or JSON object, AND the `Content-Type` is clearly supplied by the provider, it will be put in `res.obj`.
* If the response is not an object, or is declared as `text/plain` or other unparseable format, the `res.obj` will be undefined
* The definition of the response payload (i.e. the response schema) is available for tools at `client.models['yourModelName'].definition`

Thus, sometimes the response is not parseable, or it isn't desired to be parsed.  Thus we give the caller the choice to see what the raw value was, or even the unparsed representation of the parsed object.  So we don't choose.  It's like Burger King, you can Have it your Way (tm)

**Comment by mbana** [comment]
For example:

* http://editor.swagger.io/#/
* When you make the call to /persons It returns `ArrayOfPersons`.
* If you make this call in the JS client, you're returned an "plain" Array.
* It would be nice, if the actual `res.obj` contained meta information about what structure of the object.

Hope that's clear.
